include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false
    sort_pub_dependencies: false
    flutter_style_todos: false
    prefer_asserts_with_message: false
    no_default_cases: false

analyzer:
  errors:
    invalid_annotation_target: ignore

  exclude:
    - "**.*.dart"